hyperparams:
  epoch_count: 10
  batch_size: 8
  batch_fit: 7
  mean: [0.2845,0.3257,0.2874]
  std: [0.1878,0.1899,0.1874]
  start_epoch: 0
  epochs: 50
  warmup_epochs: 4
  weight_decay: 0.05
  base_lr: 0.0005
  warmup_lr: 0.0000005
  min_lr: 0.000005
  clip_grad: 5.0
  auto_resume: True
  accumalation_steps: 1
  use_checkpoint: False
  scheduler_name: cosine
  decay_epochs: 5
  decay_rate: 0.1
  optimzer_name: adamw
  optimizer_eps: 1e-8
  optimizer_beta1: 0.9
  optimizer_beta2: 0.999
  optimizer_momentum: 0.9
