defaults:
 - kitti: defaults
 - cityscapes: defaults
 - kitti_tulsiani: defaults
 - wandb: defaults
 - simulation: defaults
 - _self_
settings:
  wandb: True
  rendering: True
  perceptual_loss: False
  output_image: 0
  loss_functions: {1: L1Loss, 2: MSELoss, 3: SmoothL1Loss, 4: BCELoss}
  loss_option: 2
  models: {1: SWIN, 2: UNet, 3: VNet}
  model_option: 1